[package]
name = "awkvm"
version = "0.1.0"
edition = "2024"
description = "Compile LLVM IR to gawk script"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
llvm-ir = { version = "0.11", features = ["llvm-19"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "awkvm"
path = "src/main.rs"
