[package]
name = "awkvm"
version = "0.3.1"
edition = "2024"
description = "Compile LLVM IR to gawk script"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
either = "1"
llvm-ir = { version = "0.11", features = ["llvm-19"] }
tempfile = "3"

[lib]
path = "src/lib.rs"

[[bin]]
name = "awkvm"
path = "src/main.rs"
