use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

use anyhow::{Result, anyhow, bail};
use llvm_ir::{Module, Type, TypeRef, function::Parameter, types::FPType};

use crate::runtime::{LIBC, RUNTIME};

mod annotate;
mod call;
mod func;
mod globals;
mod mem;
mod names;
mod probe_map;
mod types;

const MAX_ICALL_ARITY: usize = 8;

use names::{canonical_fn_name, func_to_var, name_to_var};
use probe_map::PROBE_MAP;
use types::LayoutCx;

pub fn emit(
    module: &Module,
    inline_asm: &[(String, String)],
    linked: &[String],
    library: bool,
) -> Result<String> {
    let mut out = String::new();
    let _ = writeln!(out, "# Generated by awkvm from {}", module.name);
    let _ = writeln!(out, "# Requires gawk (uses and/or/xor/lshift/rshift built-ins)");
    let _ = writeln!(out);

    let _ = writeln!(out, "{RUNTIME}");

    // Linked awk: any `--link <file>` arg's content is emitted verbatim
    // right after the runtime so it can use _alloc / _cstr / _str_to_mem
    // / etc. Every `function fn_<name>(...)` defined in here becomes
    // callable from C-side `extern <T> <name>(...)` — matched up via the
    // declare-only-stub suppression below.
    let mut linked_fn_c_names: HashSet<String> = HashSet::new();
    for awk in linked {
        out.push_str(awk);
        if !awk.ends_with('\n') {
            out.push('\n');
        }
        linked_fn_c_names.extend(extract_link_fn_names(awk));
    }
    let _ = writeln!(out);

    let fn_ids = build_fn_ids(module);
    let mut cx = LayoutCx::new(&module.types, inline_asm);

    globals::emit_globals_init(&mut out, module, &fn_ids, &mut cx)?;

    // Library mode (`awkvm --library`) skips the `BEGIN { exit fn_main() }`
    // boot line so the emitted script can be loaded as a gawk library
    // (`gawk -f lib.awk -f script.awk`). The function bodies are still
    // emitted; external callers reach them through `awkvm_export` wrappers
    // emitted at the bottom of this file.
    if !library {
        if let Some(main_fn) = module.functions.iter().find(|f| f.name == "main") {
            match main_fn.parameters.len() {
                0 => {
                    let _ = writeln!(out, "BEGIN {{ exit fn_main() }}");
                }
                2 => {
                    // int main(int argc, char** argv)
                    let _ = writeln!(out, "BEGIN {{ exit fn_main(ARGC, _build_argv()) }}");
                }
                3 => {
                    // int main(int argc, char** argv, char** envp) — we don't
                    // model env, so pass NULL.
                    let _ = writeln!(out, "BEGIN {{ exit fn_main(ARGC, _build_argv(), 0) }}");
                }
                n => bail!("main has {n} parameters; only 0, 2, or 3 are supported"),
            }
            let _ = writeln!(out);
        }
    }

    // `__attribute__((annotate("awkvm_fn(args) { body }")))` lets the
    // user supply the awk body for a function directly, bypassing IR
    // translation. The `(args)` list provides the awk parameter names
    // (clang -O1 strips C-source param names; explicit naming avoids
    // a silent mismatch where the body references variables that
    // don't exist in the emitted scope).
    let annotations = annotate::collect(module);
    let awk_fns: HashMap<&str, &str> = annotations
        .iter()
        .filter_map(|(name, text)| {
            text.strip_prefix("awkvm_fn")
                .map(|rest| (name.as_str(), rest))
        })
        .collect();

    for func in &module.functions {
        if let Some(rest) = awk_fns.get(canonical_fn_name(func.name.as_str())) {
            emit_awk_fn(&mut out, &func.name, &func.parameters, rest)?;
        } else {
            func::emit_function(&mut out, func, &mut cx)?;
        }
    }

    // libc / Itanium ABI helpers. Skip any that the user has provided their
    // own definition of (custom operator new, malloc override, etc.) — their
    // body has already been emitted above as fn_<name>.
    let user_defined: HashSet<&str> = module
        .functions
        .iter()
        .filter(|f| !f.basic_blocks.is_empty())
        .map(|f| canonical_fn_name(f.name.as_str()))
        .collect();
    let helpers = parse_libc_helpers(LIBC);
    let helper_names: HashSet<&str> = helpers.iter().map(|(n, _)| n.as_str()).collect();
    let probe_names: HashSet<&str> = PROBE_MAP.iter().map(|(m, _)| *m).collect();

    // Toolchain coupling check: warn loudly when the user's IR
    // references a libc++ symbol whose tag-stripped form matches a
    // probe entry but whose full mangled name doesn't. That's almost
    // always an Apple-Clang-vs-Homebrew-Clang style mismatch — both
    // libc++ versions name the same function, but tag it with their
    // own ABI version (e.g. `B8ne190102` vs `B8ne190107`), so the
    // recognized-call path silently degrades to a no-op stub.
    let probe_stripped: HashSet<String> =
        PROBE_MAP.iter().map(|(m, _)| strip_abi_tags(m)).collect();
    // Walk both functions and func_declarations: at -O1 the templated
    // libc++ helpers stay external (declarations only) and our probes
    // capture them; at -O0 clang fully inlines them into user.ll as
    // user-defined function bodies. Either way they show up in the IR
    // and can mismatch on ABI tag.
    let mismatched: HashSet<String> = module
        .functions
        .iter()
        .map(|f| f.name.as_str())
        .chain(module.func_declarations.iter().map(|d| d.name.as_str()))
        .filter(|name| !probe_names.contains(name))
        .filter_map(|name| {
            let stripped = strip_abi_tags(name);
            if probe_stripped.contains(&stripped) {
                Some(format!("{name}\n  Tag-stripped form: {stripped}"))
            } else {
                None
            }
        })
        .collect();
    for entry in &mismatched {
        eprintln!(
            "awkvm: warning: `{entry}`\n  This looks like a probe-targeted \
             libc++ symbol whose ABI tag doesn't match PROBE_MAP. Calls \
             route to a no-op stub (or to a user-body wrapper that itself \
             calls a no-op stub), so output silently degrades. Hint: did \
             your .ll come from a different clang than $LLVM_SYS_191_PREFIX? \
             See LIMITATIONS.md \"Toolchain coupling\"."
        );
    }

    // Stubs for `declare`-only functions: any libc / Itanium symbol the
    // program references but doesn't define. Skip those covered by helpers
    // (which are about to be emitted as fn_<name>) or by the probe map
    // (whose call sites have been rewritten in-line, so fn_<name> is dead
    // code we'd rather not emit at all).
    for decl in &module.func_declarations {
        let canon = canonical_fn_name(decl.name.as_str());
        if helper_names.contains(canon)
            || probe_names.contains(canon)
            || linked_fn_c_names.contains(canon)
        {
            continue;
        }
        // `awkvm_fn` annotation on a declare-only function: emit the
        // body just like for full definitions. Lets users skip writing
        // a placeholder C body when they don't want to dual-build.
        if let Some(rest) = awk_fns.get(canon) {
            emit_awk_fn(&mut out, &decl.name, &decl.parameters, rest)?;
            continue;
        }
        let params: Vec<String> = decl
            .parameters
            .iter()
            .map(|p| name_to_var(&p.name))
            .collect();
        let _ = writeln!(
            &mut out,
            "function {}({}) {{}}",
            func_to_var(&decl.name),
            params.join(", ")
        );
    }
    let _ = writeln!(&mut out);

    for (name, body) in &helpers {
        if user_defined.contains(name.as_str()) {
            continue;
        }
        out.push_str(body);
        out.push('\n');
    }
    let _ = writeln!(&mut out);

    // `__attribute__((annotate("awkvm_export")))` exposes a C function to
    // outside awk callers under its bare C name (no `fn_` prefix). We emit
    // a thin forwarding wrapper rather than renaming the body so internal
    // C-side callers still resolve `name` → `fn_<name>` through the normal
    // codegen path. Pair with `--library` (which skips the
    // `BEGIN { exit fn_main() }` boot) and `gawk -f lib.awk -f script.awk`.
    //
    // Type check: only primitives (int / long / unsigned / double / bool /
    // char / void) cross the boundary in v0.2.0. Pointer / struct support
    // needs a marshaling layer and is deferred.
    let exports: Vec<&str> = annotations
        .iter()
        .filter(|(_, text)| text.as_str() == "awkvm_export")
        .map(|(name, _)| name.as_str())
        .collect();
    if !exports.is_empty() {
        emit_export_wrappers(&mut out, module, &exports, &awk_fns)?;
    }

    globals::emit_icall_dispatcher(&mut out, module, &fn_ids)?;
    Ok(out)
}

fn emit_export_wrappers(
    out: &mut String,
    module: &Module,
    exports: &[&str],
    awk_fns: &HashMap<&str, &str>,
) -> Result<()> {
    for &name in exports {
        let (parameters, return_type) = if let Some(f) =
            module.functions.iter().find(|f| f.name == name)
        {
            (f.parameters.as_slice(), &f.return_type)
        } else if let Some(d) = module.func_declarations.iter().find(|d| d.name == name) {
            // Declare-only is only valid if there's an `awkvm_fn` body
            // backing it. Otherwise the wrapper would forward into a
            // generated empty stub.
            if !awk_fns.contains_key(name) {
                bail!(
                    "awkvm_export: function `{name}` has no body in this \
                     module. Either define the body in C, or supply one via \
                     `awkvm_fn(args) {{ body }}`."
                );
            }
            (d.parameters.as_slice(), &d.return_type)
        } else {
            bail!("awkvm_export: function `{name}` not found in module");
        };

        check_export_signature(name, parameters, return_type)?;

        let params: Vec<String> = (0..parameters.len()).map(|i| format!("p{i}")).collect();
        let arglist = params.join(", ");
        let internal = func_to_var(name);
        let is_void = matches!(return_type.as_ref(), Type::VoidType);
        let prefix = if is_void { "" } else { "return " };
        let _ = writeln!(
            out,
            "function {name}({arglist}) {{ {prefix}{internal}({arglist}) }}"
        );
    }
    let _ = writeln!(out);
    Ok(())
}

// Reject non-primitive parameter / return types on `awkvm_export`
// functions. Pointers, structs, and aggregates need a marshaling
// convention (string vs byte buffer vs by-value vs by-reference) that
// we haven't designed yet — bail at codegen with a pointer to the
// follow-up wrapper layer rather than silently emitting a wrapper
// that passes raw addresses across.
fn check_export_signature(
    fn_name: &str,
    parameters: &[Parameter],
    return_type: &TypeRef,
) -> Result<()> {
    for (i, p) in parameters.iter().enumerate() {
        check_primitive(&p.ty, &format!("parameter {i} of `{fn_name}`"), false)?;
    }
    check_primitive(return_type, &format!("return type of `{fn_name}`"), true)?;
    Ok(())
}

fn check_primitive(ty: &TypeRef, what: &str, allow_void: bool) -> Result<()> {
    let ok = match ty.as_ref() {
        Type::IntegerType { bits } => matches!(*bits, 1 | 8 | 16 | 32 | 64),
        Type::FPType(FPType::Single | FPType::Double) => true,
        Type::VoidType => allow_void,
        _ => false,
    };
    if !ok {
        bail!(
            "awkvm_export: {what} is `{ty}`. Only primitive types \
             (int / long / unsigned / double / bool / char{}) cross the \
             v0.2.0 export boundary; pointer / struct support is deferred \
             to a follow-up marshaling layer.",
            if allow_void { " / void" } else { "" }
        );
    }
    Ok(())
}

// Walks libc.awk and returns each helper as (c_name, awk_function_text).
// Each helper is one `function fn_<c_name>(...) { ... }` definition; lines
// preceding it (comments, blanks) are dropped — they document the source
// file but aren't useful in the generated script. Brace balance is tracked
// so a one-liner block like `function fn_atol(s) { return _atoi(s) }` and
// a multi-line body both work.
fn parse_libc_helpers(text: &str) -> Vec<(String, String)> {
    fn brace_delta(s: &str) -> i32 {
        s.matches('{').count() as i32 - s.matches('}').count() as i32
    }
    let mut out: Vec<(String, String)> = Vec::new();
    let mut iter = text.lines().peekable();
    while let Some(line) = iter.next() {
        let trimmed = line.trim_start();
        let Some(after) = trimmed.strip_prefix("function fn_") else {
            continue;
        };
        let end = after
            .find(|c: char| c == '(' || c.is_whitespace())
            .expect("malformed libc.awk: function header without '('");
        let name = after[..end].to_string();
        let mut body = String::from(line);
        let mut depth = brace_delta(line);
        while depth > 0 {
            let next = iter
                .next()
                .expect("malformed libc.awk: unbalanced braces in helper body");
            body.push('\n');
            body.push_str(next);
            depth += brace_delta(next);
        }
        body.push('\n');
        out.push((name, body));
    }
    out
}

// Emit a function whose body is supplied verbatim by an
// `awkvm_fn(args) { body }` annotation, instead of translated from
// the IR. The signature still comes from the C declaration so type
// safety on the caller side is preserved; the awk parameter names
// come from the `(args)` list so the body can refer to them by
// the same names the C source uses.
//
// `rest` is what's left of the annotation after stripping the
// `awkvm_fn` prefix — `(args) { body }`.
fn emit_awk_fn(
    out: &mut String,
    fn_name: &str,
    parameters: &[Parameter],
    rest: &str,
) -> Result<()> {
    let (names, body) = parse_awk_fn_annotation(rest, fn_name)?;
    if names.len() != parameters.len() {
        bail!(
            "awkvm_fn annotation for `{fn_name}` declares {} parameter \
             name(s) but the C function has {}",
            names.len(),
            parameters.len()
        );
    }
    let params: Vec<String> = names.into_iter().map(String::from).collect();
    let _ = writeln!(
        out,
        "function {}({}) {{",
        func_to_var(fn_name),
        params.join(", ")
    );
    for line in dedent_body(body) {
        let _ = writeln!(out, "    {line}");
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    Ok(())
}

// Parse the body portion of an `awkvm_fn(args) { body }` annotation.
// `text` is what's left after the `awkvm_fn` prefix.
fn parse_awk_fn_annotation<'a>(
    text: &'a str,
    fn_name: &str,
) -> Result<(Vec<&'a str>, &'a str)> {
    let after_paren = text.strip_prefix('(').ok_or_else(|| {
        anyhow!(
            "awkvm_fn annotation for `{fn_name}` should look like \
             `awkvm_fn(args) {{body}}`, got `awkvm_fn{text}`"
        )
    })?;
    let close = after_paren
        .find(')')
        .ok_or_else(|| anyhow!("awkvm_fn annotation for `{fn_name}` has unmatched `(`"))?;
    let names: Vec<&str> = after_paren[..close]
        .split(',')
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .collect();
    let after_args = after_paren[close + 1..].trim_start();
    let after_brace = after_args.strip_prefix('{').ok_or_else(|| {
        anyhow!(
            "awkvm_fn annotation for `{fn_name}` is missing `{{` between \
             the parameter list and the body"
        )
    })?;
    let trimmed = after_brace.trim_end();
    let body = trimmed.strip_suffix('}').ok_or_else(|| {
        anyhow!(
            "awkvm_fn annotation for `{fn_name}` is missing closing `}}`"
        )
    })?;
    Ok((names, body))
}

// Trim leading / trailing blank lines and strip the common leading
// whitespace from a multi-line body so user-written indentation
// translates cleanly into the emitted awk function.
fn dedent_body(body: &str) -> Vec<String> {
    let lines: Vec<&str> = body.lines().collect();
    let start = lines
        .iter()
        .position(|l| !l.trim().is_empty())
        .unwrap_or(lines.len());
    let end = lines
        .iter()
        .rposition(|l| !l.trim().is_empty())
        .map(|p| p + 1)
        .unwrap_or(0);
    if start >= end {
        return Vec::new();
    }
    let core = &lines[start..end];
    let common = core
        .iter()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.len() - l.trim_start().len())
        .min()
        .unwrap_or(0);
    core.iter()
        .map(|l| {
            if l.trim().is_empty() {
                String::new()
            } else {
                l[common..].to_string()
            }
        })
        .collect()
}

// Extract the C-level names of every `function fn_<name>(...)`
// definition in linked awk text. Used by emit() to suppress
// declare-only stubs whose name matches a linked definition (without
// suppression awk would see two `fn_<name>` definitions and refuse
// to parse). The linked function must be on its own line starting
// with optional whitespace + `function fn_`; closing-brace placement
// and body content don't matter to this scanner.
fn extract_link_fn_names(text: &str) -> HashSet<String> {
    let mut out = HashSet::new();
    for line in text.lines() {
        let trimmed = line.trim_start();
        let Some(after) = trimmed.strip_prefix("function fn_") else {
            continue;
        };
        let end = after
            .find(|c: char| !(c.is_alphanumeric() || c == '_'))
            .unwrap_or(after.len());
        if end == 0 {
            continue;
        }
        let rest = after[end..].trim_start();
        if !rest.starts_with('(') {
            continue;
        }
        out.insert(after[..end].to_string());
    }
    out
}

// Strip Itanium ABI tags (`B<length><tag-chars>`) from a mangled name.
// Used to detect toolchain mismatches: two libc++ versions naming the
// same templated helper differ only in the tag content (e.g.
// `B8ne190102` vs `B8ne190107`), so both reduce to the same canonical
// form after stripping.
fn strip_abi_tags(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = String::with_capacity(s.len());
    let mut i = 0;
    while i < bytes.len() {
        // ABI-tag prefix: `B` followed by an ASCII digit sequence
        // giving the tag length, then that many tag-chars.
        if bytes[i] == b'B' && i + 1 < bytes.len() && bytes[i + 1].is_ascii_digit() {
            let mut j = i + 1;
            let mut len = 0usize;
            while j < bytes.len() && bytes[j].is_ascii_digit() {
                len = len * 10 + (bytes[j] - b'0') as usize;
                j += 1;
            }
            if j + len <= bytes.len() {
                i = j + len;
                continue;
            }
        }
        out.push(bytes[i] as char);
        i += 1;
    }
    out
}

// Assign sequential ids (starting at 1; 0 reserved for null) to every defined
// function. Declared-only functions are skipped — they have no awk body.
fn build_fn_ids(module: &Module) -> HashMap<String, i64> {
    module
        .functions
        .iter()
        .filter(|f| !f.basic_blocks.is_empty())
        .enumerate()
        .map(|(i, f)| (f.name.clone(), (i + 1) as i64))
        .collect()
}
