use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

use anyhow::{Result, bail};
use llvm_ir::Module;

use crate::runtime::{LIBC, RUNTIME};

mod call;
mod func;
mod globals;
mod mem;
mod names;
mod types;

const MAX_ICALL_ARITY: usize = 8;

use names::{func_to_var, name_to_var};
use types::LayoutCx;

pub fn emit(module: &Module) -> Result<String> {
    let mut out = String::new();
    let _ = writeln!(out, "# Generated by awkvm from {}", module.name);
    let _ = writeln!(out, "# Requires gawk (uses and/or/xor/lshift/rshift built-ins)");
    let _ = writeln!(out);

    let _ = writeln!(out, "{RUNTIME}");

    let fn_ids = build_fn_ids(module);
    let mut cx = LayoutCx::new(&module.types);

    globals::emit_globals_init(&mut out, module, &fn_ids, &mut cx)?;

    if let Some(main_fn) = module.functions.iter().find(|f| f.name == "main") {
        match main_fn.parameters.len() {
            0 => {
                let _ = writeln!(out, "BEGIN {{ exit fn_main() }}");
            }
            2 => {
                // int main(int argc, char** argv)
                let _ = writeln!(out, "BEGIN {{ exit fn_main(ARGC, _build_argv()) }}");
            }
            3 => {
                // int main(int argc, char** argv, char** envp) — we don't
                // model env, so pass NULL.
                let _ = writeln!(out, "BEGIN {{ exit fn_main(ARGC, _build_argv(), 0) }}");
            }
            n => bail!("main has {n} parameters; only 0, 2, or 3 are supported"),
        }
        let _ = writeln!(out);
    }

    for func in &module.functions {
        func::emit_function(&mut out, func, &mut cx)?;
    }

    // libc / Itanium ABI helpers. Skip any that the user has provided their
    // own definition of (custom operator new, malloc override, etc.) — their
    // body has already been emitted above as fn_<name>.
    let user_defined: HashSet<&str> = module
        .functions
        .iter()
        .filter(|f| !f.basic_blocks.is_empty())
        .map(|f| f.name.as_str())
        .collect();
    let helpers = parse_libc_helpers(LIBC);
    let helper_names: HashSet<&str> = helpers.iter().map(|(n, _)| n.as_str()).collect();

    // Stubs for `declare`-only functions: any libc / Itanium symbol the
    // program references but doesn't define. Skip those covered by the
    // helpers we're about to emit, otherwise gawk would see two definitions
    // of fn_<name> and refuse to parse.
    for decl in &module.func_declarations {
        if helper_names.contains(decl.name.as_str()) {
            continue;
        }
        let params: Vec<String> = decl
            .parameters
            .iter()
            .map(|p| name_to_var(&p.name))
            .collect();
        let _ = writeln!(
            &mut out,
            "function {}({}) {{}}",
            func_to_var(&decl.name),
            params.join(", ")
        );
    }
    let _ = writeln!(&mut out);

    for (name, body) in &helpers {
        if user_defined.contains(name.as_str()) {
            continue;
        }
        out.push_str(body);
        out.push('\n');
    }
    let _ = writeln!(&mut out);

    globals::emit_icall_dispatcher(&mut out, module, &fn_ids)?;
    Ok(out)
}

// Walks libc.awk and returns each helper as (c_name, awk_function_text).
// Each helper is one `function fn_<c_name>(...) { ... }` definition; lines
// preceding it (comments, blanks) are dropped — they document the source
// file but aren't useful in the generated script. Brace balance is tracked
// so a one-liner block like `function fn_atol(s) { return _atoi(s) }` and
// a multi-line body both work.
fn parse_libc_helpers(text: &str) -> Vec<(String, String)> {
    fn brace_delta(s: &str) -> i32 {
        s.matches('{').count() as i32 - s.matches('}').count() as i32
    }
    let mut out: Vec<(String, String)> = Vec::new();
    let mut iter = text.lines().peekable();
    while let Some(line) = iter.next() {
        let trimmed = line.trim_start();
        let Some(after) = trimmed.strip_prefix("function fn_") else {
            continue;
        };
        let end = after
            .find(|c: char| c == '(' || c.is_whitespace())
            .expect("malformed libc.awk: function header without '('");
        let name = after[..end].to_string();
        let mut body = String::from(line);
        let mut depth = brace_delta(line);
        while depth > 0 {
            let next = iter
                .next()
                .expect("malformed libc.awk: unbalanced braces in helper body");
            body.push('\n');
            body.push_str(next);
            depth += brace_delta(next);
        }
        body.push('\n');
        out.push((name, body));
    }
    out
}

// Assign sequential ids (starting at 1; 0 reserved for null) to every defined
// function. Declared-only functions are skipped — they have no awk body.
fn build_fn_ids(module: &Module) -> HashMap<String, i64> {
    module
        .functions
        .iter()
        .filter(|f| !f.basic_blocks.is_empty())
        .enumerate()
        .map(|(i, f)| (f.name.clone(), (i + 1) as i64))
        .collect()
}
