use std::collections::BTreeSet;
use std::fmt::Write as _;

use anyhow::{Result, bail};
use either::Either;
use llvm_ir::{Constant, ConstantRef, Function, Instruction, Module, Name, Operand, Terminator};

pub fn emit(module: &Module) -> Result<String> {
    let mut out = String::new();
    let _ = writeln!(out, "# Generated by awkvm from {}", module.name);
    let _ = writeln!(out);

    if module.functions.iter().any(|f| f.name == "main") {
        let _ = writeln!(out, "BEGIN {{ exit fn_main() }}");
        let _ = writeln!(out);
    }

    for func in &module.functions {
        emit_function(&mut out, func)?;
    }
    Ok(out)
}

fn emit_function(out: &mut String, func: &Function) -> Result<()> {
    if func.basic_blocks.len() != 1 {
        bail!(
            "function `{}` has {} basic blocks; multi-block control flow is not implemented yet",
            func.name,
            func.basic_blocks.len()
        );
    }
    let bb = &func.basic_blocks[0];

    let params: Vec<String> = func.parameters.iter().map(|p| name_to_var(&p.name)).collect();

    let mut locals: BTreeSet<String> = BTreeSet::new();
    for instr in &bb.instrs {
        if let Some(name) = instruction_dest(instr) {
            let var = name_to_var(name);
            if !params.contains(&var) {
                locals.insert(var);
            }
        }
    }

    let _ = write!(out, "function {}(", func_to_var(&func.name));
    let _ = write!(out, "{}", params.join(", "));
    if !locals.is_empty() {
        let sep = if params.is_empty() { "    " } else { ",    " };
        let locals_csv = locals.iter().cloned().collect::<Vec<_>>().join(", ");
        let _ = write!(out, "{sep}{locals_csv}");
    }
    let _ = writeln!(out, ") {{");

    for instr in &bb.instrs {
        emit_instruction(out, instr)?;
    }
    emit_terminator(out, &bb.term)?;

    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    Ok(())
}

fn instruction_dest(instr: &Instruction) -> Option<&Name> {
    use Instruction::*;
    match instr {
        Add(i) => Some(&i.dest),
        Sub(i) => Some(&i.dest),
        Mul(i) => Some(&i.dest),
        SDiv(i) => Some(&i.dest),
        SRem(i) => Some(&i.dest),
        Call(i) => i.dest.as_ref(),
        _ => None,
    }
}

fn emit_instruction(out: &mut String, instr: &Instruction) -> Result<()> {
    use Instruction::*;
    match instr {
        Add(i) => binop(out, &i.dest, &i.operand0, "+", &i.operand1),
        Sub(i) => binop(out, &i.dest, &i.operand0, "-", &i.operand1),
        Mul(i) => binop(out, &i.dest, &i.operand0, "*", &i.operand1),
        SDiv(i) => {
            // LLVM `sdiv` truncates toward zero (C99). awk's int() also
            // truncates toward zero, so int(a/b) is correct.
            let _ = writeln!(
                out,
                "    {} = int({} / {})",
                name_to_var(&i.dest),
                operand_str(&i.operand0),
                operand_str(&i.operand1)
            );
            Ok(())
        }
        SRem(i) => {
            // a - trunc(a/b) * b — matches LLVM signed remainder semantics.
            let dest = name_to_var(&i.dest);
            let a = operand_str(&i.operand0);
            let b = operand_str(&i.operand1);
            let _ = writeln!(out, "    {dest} = {a} - int({a} / {b}) * {b}");
            Ok(())
        }
        Call(call) => emit_call(out, call),
        other => bail!("instruction not implemented: {other}"),
    }
}

fn binop(out: &mut String, dest: &Name, lhs: &Operand, op: &str, rhs: &Operand) -> Result<()> {
    let _ = writeln!(
        out,
        "    {} = {} {op} {}",
        name_to_var(dest),
        operand_str(lhs),
        operand_str(rhs)
    );
    Ok(())
}

fn emit_call(out: &mut String, call: &llvm_ir::instruction::Call) -> Result<()> {
    let target = match &call.function {
        Either::Right(Operand::ConstantOperand(c)) => match c.as_ref() {
            Constant::GlobalReference { name, .. } => match name {
                Name::Name(s) => format!("fn_{}", sanitize(s)),
                Name::Number(n) => format!("fn_{n}"),
            },
            _ => bail!("indirect call target is not a global reference"),
        },
        Either::Right(_) => bail!("indirect calls are not implemented yet"),
        Either::Left(_) => bail!("inline assembly is not supported"),
    };

    let args: Vec<String> = call.arguments.iter().map(|(op, _)| operand_str(op)).collect();
    let call_expr = format!("{target}({})", args.join(", "));

    match &call.dest {
        Some(dest) => {
            let _ = writeln!(out, "    {} = {call_expr}", name_to_var(dest));
        }
        None => {
            let _ = writeln!(out, "    {call_expr}");
        }
    }
    Ok(())
}

fn emit_terminator(out: &mut String, term: &Terminator) -> Result<()> {
    use Terminator::*;
    match term {
        Ret(r) => {
            match &r.return_operand {
                Some(op) => {
                    let _ = writeln!(out, "    return {}", operand_str(op));
                }
                None => {
                    let _ = writeln!(out, "    return");
                }
            }
            Ok(())
        }
        other => bail!("terminator not implemented: {other}"),
    }
}

fn operand_str(op: &Operand) -> String {
    match op {
        Operand::LocalOperand { name, .. } => name_to_var(name),
        Operand::ConstantOperand(c) => constant_str(c),
        Operand::MetadataOperand => "0".to_string(),
    }
}

fn constant_str(c: &ConstantRef) -> String {
    match c.as_ref() {
        Constant::Int { value, bits } => sign_extend(*value, *bits).to_string(),
        Constant::Null(_) => "0".to_string(),
        Constant::AggregateZero(_) => "0".to_string(),
        other => format!("0 /* unsupported constant: {other} */"),
    }
}

fn sign_extend(value: u64, bits: u32) -> i64 {
    if bits >= 64 {
        return value as i64;
    }
    let shift = 64 - bits;
    ((value as i64) << shift) >> shift
}

fn name_to_var(name: &Name) -> String {
    match name {
        Name::Number(n) => format!("r{n}"),
        Name::Name(s) => format!("r_{}", sanitize(s)),
    }
}

fn func_to_var(name: &str) -> String {
    format!("fn_{}", sanitize(name))
}

fn sanitize(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}
