use std::collections::BTreeSet;
use std::fmt::Write as _;

use anyhow::{Result, anyhow, bail};
use either::Either;
use llvm_ir::{
    Constant, ConstantRef, Function, Instruction, IntPredicate, Module, Name, Operand, Terminator,
    Type, TypeRef,
};

const RUNTIME: &str = r#"function _ashr(a, n) {
    return (a < 0 && a % (2 ^ n) != 0) ? int(a / (2 ^ n)) - 1 : int(a / (2 ^ n))
}
function _zext(a, w) {
    return a < 0 ? a + (2 ^ w) : a
}
function _trunc(a, w,    m) {
    m = and(a, (2 ^ w) - 1)
    return m >= (2 ^ (w - 1)) ? m - (2 ^ w) : m
}
"#;

pub fn emit(module: &Module) -> Result<String> {
    let mut out = String::new();
    let _ = writeln!(out, "# Generated by awkvm from {}", module.name);
    let _ = writeln!(out, "# Requires gawk (uses and/or/xor/lshift/rshift built-ins)");
    let _ = writeln!(out);

    let _ = writeln!(out, "{RUNTIME}");

    if module.functions.iter().any(|f| f.name == "main") {
        let _ = writeln!(out, "BEGIN {{ exit fn_main() }}");
        let _ = writeln!(out);
    }

    for func in &module.functions {
        emit_function(&mut out, func)?;
    }
    Ok(out)
}

fn emit_function(out: &mut String, func: &Function) -> Result<()> {
    let params: Vec<String> = func.parameters.iter().map(|p| name_to_var(&p.name)).collect();
    let multi_block = func.basic_blocks.len() > 1;

    let mut locals: BTreeSet<String> = BTreeSet::new();
    for bb in &func.basic_blocks {
        for instr in &bb.instrs {
            if let Some(name) = instruction_dest(instr) {
                let var = name_to_var(name);
                if !params.contains(&var) {
                    locals.insert(var);
                }
            }
        }
    }
    if multi_block {
        locals.insert("block".to_string());
    }

    let _ = write!(out, "function {}(", func_to_var(&func.name));
    let _ = write!(out, "{}", params.join(", "));
    if !locals.is_empty() {
        let sep = if params.is_empty() { "    " } else { ",    " };
        let locals_csv = locals.iter().cloned().collect::<Vec<_>>().join(", ");
        let _ = write!(out, "{sep}{locals_csv}");
    }
    let _ = writeln!(out, ") {{");

    if multi_block {
        emit_multi_block(out, func)?;
    } else {
        let bb = &func.basic_blocks[0];
        for instr in &bb.instrs {
            emit_instruction(out, instr, "    ")?;
        }
        emit_terminator(out, &bb.term, &bb.name, func, "    ")?;
    }

    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    Ok(())
}

fn emit_multi_block(out: &mut String, func: &Function) -> Result<()> {
    let entry = &func.basic_blocks[0];
    let _ = writeln!(out, "    block = \"{}\"", block_label(&entry.name));
    let _ = writeln!(out, "    while (1) {{");
    for (i, bb) in func.basic_blocks.iter().enumerate() {
        let kw = if i == 0 { "if" } else { "else if" };
        let _ = writeln!(out, "        {kw} (block == \"{}\") {{", block_label(&bb.name));
        for instr in &bb.instrs {
            emit_instruction(out, instr, "            ")?;
        }
        emit_terminator(out, &bb.term, &bb.name, func, "            ")?;
        let _ = writeln!(out, "        }}");
    }
    let _ = writeln!(out, "    }}");
    Ok(())
}

fn instruction_dest(instr: &Instruction) -> Option<&Name> {
    use Instruction::*;
    match instr {
        Add(i) => Some(&i.dest),
        Sub(i) => Some(&i.dest),
        Mul(i) => Some(&i.dest),
        SDiv(i) => Some(&i.dest),
        SRem(i) => Some(&i.dest),
        Shl(i) => Some(&i.dest),
        LShr(i) => Some(&i.dest),
        AShr(i) => Some(&i.dest),
        And(i) => Some(&i.dest),
        Or(i) => Some(&i.dest),
        Xor(i) => Some(&i.dest),
        ZExt(i) => Some(&i.dest),
        SExt(i) => Some(&i.dest),
        Trunc(i) => Some(&i.dest),
        Select(i) => Some(&i.dest),
        ICmp(i) => Some(&i.dest),
        Phi(i) => Some(&i.dest),
        Call(i) => i.dest.as_ref(),
        _ => None,
    }
}

fn emit_instruction(out: &mut String, instr: &Instruction, indent: &str) -> Result<()> {
    use Instruction::*;
    match instr {
        Add(i) => binop(out, indent, &i.dest, &i.operand0, "+", &i.operand1),
        Sub(i) => binop(out, indent, &i.dest, &i.operand0, "-", &i.operand1),
        Mul(i) => binop(out, indent, &i.dest, &i.operand0, "*", &i.operand1),
        SDiv(i) => {
            let _ = writeln!(
                out,
                "{indent}{} = int({} / {})",
                name_to_var(&i.dest),
                operand_str(&i.operand0),
                operand_str(&i.operand1)
            );
            Ok(())
        }
        SRem(i) => {
            let dest = name_to_var(&i.dest);
            let a = operand_str(&i.operand0);
            let b = operand_str(&i.operand1);
            let _ = writeln!(out, "{indent}{dest} = {a} - int({a} / {b}) * {b}");
            Ok(())
        }
        Shl(i) => fn_call(out, indent, &i.dest, "lshift", &[&i.operand0, &i.operand1]),
        LShr(i) => fn_call(out, indent, &i.dest, "rshift", &[&i.operand0, &i.operand1]),
        AShr(i) => fn_call(out, indent, &i.dest, "_ashr", &[&i.operand0, &i.operand1]),
        And(i) => fn_call(out, indent, &i.dest, "and", &[&i.operand0, &i.operand1]),
        Or(i) => fn_call(out, indent, &i.dest, "or", &[&i.operand0, &i.operand1]),
        Xor(i) => fn_call(out, indent, &i.dest, "xor", &[&i.operand0, &i.operand1]),
        ZExt(i) => {
            let from_bits = operand_bits(&i.operand)?;
            let _ = writeln!(
                out,
                "{indent}{} = _zext({}, {from_bits})",
                name_to_var(&i.dest),
                operand_str(&i.operand)
            );
            Ok(())
        }
        SExt(i) => {
            // Our integer encoding is already sign-extended at all widths,
            // so widening is a no-op.
            let _ = writeln!(
                out,
                "{indent}{} = {}",
                name_to_var(&i.dest),
                operand_str(&i.operand)
            );
            Ok(())
        }
        Trunc(i) => {
            let to_bits = type_bits(&i.to_type)?;
            let _ = writeln!(
                out,
                "{indent}{} = _trunc({}, {to_bits})",
                name_to_var(&i.dest),
                operand_str(&i.operand)
            );
            Ok(())
        }
        Select(i) => {
            let _ = writeln!(
                out,
                "{indent}{} = {} ? {} : {}",
                name_to_var(&i.dest),
                operand_str(&i.condition),
                operand_str(&i.true_value),
                operand_str(&i.false_value),
            );
            Ok(())
        }
        ICmp(i) => binop(out, indent, &i.dest, &i.operand0, icmp_op(i.predicate), &i.operand1),
        Phi(_) => Ok(()),
        Call(call) => emit_call(out, call, indent),
        other => bail!("instruction not implemented: {other}"),
    }
}

fn icmp_op(p: IntPredicate) -> &'static str {
    // Unsigned predicates currently emit signed comparison; correct only
    // for non-negative operands. Tightening this up is a follow-up.
    match p {
        IntPredicate::EQ => "==",
        IntPredicate::NE => "!=",
        IntPredicate::SGT | IntPredicate::UGT => ">",
        IntPredicate::SGE | IntPredicate::UGE => ">=",
        IntPredicate::SLT | IntPredicate::ULT => "<",
        IntPredicate::SLE | IntPredicate::ULE => "<=",
    }
}

fn binop(
    out: &mut String,
    indent: &str,
    dest: &Name,
    lhs: &Operand,
    op: &str,
    rhs: &Operand,
) -> Result<()> {
    let _ = writeln!(
        out,
        "{indent}{} = {} {op} {}",
        name_to_var(dest),
        operand_str(lhs),
        operand_str(rhs)
    );
    Ok(())
}

fn fn_call(
    out: &mut String,
    indent: &str,
    dest: &Name,
    func: &str,
    args: &[&Operand],
) -> Result<()> {
    let args_csv = args.iter().map(|a| operand_str(a)).collect::<Vec<_>>().join(", ");
    let _ = writeln!(out, "{indent}{} = {func}({args_csv})", name_to_var(dest));
    Ok(())
}

fn emit_call(out: &mut String, call: &llvm_ir::instruction::Call, indent: &str) -> Result<()> {
    let target_name = match &call.function {
        Either::Right(Operand::ConstantOperand(c)) => match c.as_ref() {
            Constant::GlobalReference { name, .. } => match name {
                Name::Name(s) => s.to_string(),
                Name::Number(n) => n.to_string(),
            },
            _ => bail!("indirect call target is not a global reference"),
        },
        Either::Right(_) => bail!("indirect calls are not implemented yet"),
        Either::Left(_) => bail!("inline assembly is not supported"),
    };

    if let Some(rest) = target_name.strip_prefix("llvm.") {
        return emit_intrinsic(out, call, indent, &target_name, rest);
    }

    let target = format!("fn_{}", sanitize(&target_name));
    let args: Vec<String> = call.arguments.iter().map(|(op, _)| operand_str(op)).collect();
    let call_expr = format!("{target}({})", args.join(", "));

    match &call.dest {
        Some(dest) => {
            let _ = writeln!(out, "{indent}{} = {call_expr}", name_to_var(dest));
        }
        None => {
            let _ = writeln!(out, "{indent}{call_expr}");
        }
    }
    Ok(())
}

fn emit_intrinsic(
    out: &mut String,
    call: &llvm_ir::instruction::Call,
    indent: &str,
    full_name: &str,
    rest: &str,
) -> Result<()> {
    let base = rest.split('.').next().unwrap_or(rest);
    let args: Vec<String> = call.arguments.iter().map(|(op, _)| operand_str(op)).collect();
    let dest = call.dest.as_ref();

    let assign = |expr: String, out: &mut String| match dest {
        Some(d) => {
            let _ = writeln!(out, "{indent}{} = {expr}", name_to_var(d));
        }
        None => {
            let _ = writeln!(out, "{indent}{expr}");
        }
    };

    match base {
        "smax" | "umax" if args.len() == 2 => {
            assign(format!("{a} > {b} ? {a} : {b}", a = args[0], b = args[1]), out);
        }
        "smin" | "umin" if args.len() == 2 => {
            assign(format!("{a} < {b} ? {a} : {b}", a = args[0], b = args[1]), out);
        }
        // llvm.abs takes (value, is_int_min_poison). We ignore the poison flag.
        "abs" if !args.is_empty() => {
            assign(format!("{a} < 0 ? -{a} : {a}", a = args[0]), out);
        }
        _ => bail!("intrinsic `{full_name}` is not implemented yet"),
    }
    Ok(())
}

fn emit_terminator(
    out: &mut String,
    term: &Terminator,
    current_block: &Name,
    func: &Function,
    indent: &str,
) -> Result<()> {
    use Terminator::*;
    match term {
        Ret(r) => {
            match &r.return_operand {
                Some(op) => {
                    let _ = writeln!(out, "{indent}return {}", operand_str(op));
                }
                None => {
                    let _ = writeln!(out, "{indent}return");
                }
            }
            Ok(())
        }
        Br(b) => emit_branch(out, indent, &b.dest, current_block, func),
        CondBr(b) => {
            let cond = operand_str(&b.condition);
            let _ = writeln!(out, "{indent}if ({cond}) {{");
            let inner = format!("{indent}    ");
            emit_branch(out, &inner, &b.true_dest, current_block, func)?;
            let _ = writeln!(out, "{indent}}} else {{");
            emit_branch(out, &inner, &b.false_dest, current_block, func)?;
            let _ = writeln!(out, "{indent}}}");
            Ok(())
        }
        Switch(s) => {
            let val = operand_str(&s.operand);
            let inner = format!("{indent}    ");
            if s.dests.is_empty() {
                emit_branch(out, indent, &s.default_dest, current_block, func)?;
            } else {
                for (i, (c, target)) in s.dests.iter().enumerate() {
                    let kw = if i == 0 { "if" } else { "else if" };
                    let _ = writeln!(out, "{indent}{kw} ({val} == {}) {{", constant_str(c));
                    emit_branch(out, &inner, target, current_block, func)?;
                    let _ = writeln!(out, "{indent}}}");
                }
                let _ = writeln!(out, "{indent}else {{");
                emit_branch(out, &inner, &s.default_dest, current_block, func)?;
                let _ = writeln!(out, "{indent}}}");
            }
            Ok(())
        }
        other => bail!("terminator not implemented: {other}"),
    }
}

fn emit_branch(
    out: &mut String,
    indent: &str,
    target: &Name,
    current_block: &Name,
    func: &Function,
) -> Result<()> {
    let target_bb = func
        .basic_blocks
        .iter()
        .find(|b| &b.name == target)
        .ok_or_else(|| anyhow!("branch target `{target}` not found in function `{}`", func.name))?;

    // Resolve phis sequentially. Correct for the common case where phi
    // destinations don't feed each other in the same block; the swap/cycle
    // case is left as a future temp-based parallel copy.
    for instr in &target_bb.instrs {
        if let Instruction::Phi(phi) = instr {
            let (val, _) = phi
                .incoming_values
                .iter()
                .find(|(_, src)| src == current_block)
                .ok_or_else(|| {
                    anyhow!(
                        "phi `{}` has no incoming value from `{current_block}` in `{}`",
                        phi.dest,
                        func.name
                    )
                })?;
            let _ = writeln!(out, "{indent}{} = {}", name_to_var(&phi.dest), operand_str(val));
        }
    }
    let _ = writeln!(out, "{indent}block = \"{}\"", block_label(target));
    Ok(())
}

fn operand_str(op: &Operand) -> String {
    match op {
        Operand::LocalOperand { name, .. } => name_to_var(name),
        Operand::ConstantOperand(c) => constant_str(c),
        Operand::MetadataOperand => "0".to_string(),
    }
}

fn constant_str(c: &ConstantRef) -> String {
    match c.as_ref() {
        Constant::Int { value, bits } => sign_extend(*value, *bits).to_string(),
        Constant::Null(_) => "0".to_string(),
        Constant::AggregateZero(_) => "0".to_string(),
        other => format!("0 /* unsupported constant: {other} */"),
    }
}

fn sign_extend(value: u64, bits: u32) -> i64 {
    if bits >= 64 {
        return value as i64;
    }
    let shift = 64 - bits;
    ((value as i64) << shift) >> shift
}

fn operand_bits(op: &Operand) -> Result<u32> {
    match op {
        Operand::LocalOperand { ty, .. } => type_bits(ty),
        Operand::ConstantOperand(c) => match c.as_ref() {
            Constant::Int { bits, .. } => Ok(*bits),
            other => bail!("operand has non-integer constant type: {other}"),
        },
        Operand::MetadataOperand => bail!("metadata operand has no bit width"),
    }
}

fn type_bits(ty: &TypeRef) -> Result<u32> {
    match ty.as_ref() {
        Type::IntegerType { bits } => Ok(*bits),
        other => bail!("expected integer type, got {other}"),
    }
}

fn name_to_var(name: &Name) -> String {
    match name {
        Name::Number(n) => format!("r{n}"),
        Name::Name(s) => format!("r_{}", sanitize(s)),
    }
}

fn func_to_var(name: &str) -> String {
    format!("fn_{}", sanitize(name))
}

fn block_label(name: &Name) -> String {
    match name {
        Name::Number(n) => format!("b{n}"),
        Name::Name(s) => format!("b_{}", sanitize(s)),
    }
}

fn sanitize(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}
